# 0. Summary
- Download the file "hubeau_{HUBEAU_DATA_ENDPOINT}_{SITE}_{min_date}_{max_date}_1.csv" from LOCAL_DATA_DIRECTORY
- Convert "date_obs_elab" to datetime
- Pivot "grandeur" quantities to columns with values "resultat"
- Save to LOCAL_DATA_DIRECTORY as "hubeau_{HUBEAU_DATA_ENDPOINT}_{SITE}_{min_date}_{max_date}_2.csv"

In [ ]:
import os
import pandas
import datetime

# LOCAL COMPONENTS:
from config import LOCAL_DATA_DIRECTORY, SITES
from utils import request_json_all, save_dataframe_as_csv

In [ ]:
print("Local data directory:", LOCAL_DATA_DIRECTORY)
assert(os.path.exists(LOCAL_DATA_DIRECTORY))

Local data directory: c:\Users\nicolas\Repositories\Jedha\Shares\M11\nowcast-flood-risk\data\hubeau

In [ ]:
HUBEAU_DATA_ENDPOINT = "obs_elab"

In [4]:
SITE = SITES["Selestat"]["code"]
STATIONS = ",".join([station["code"] for station in SITES["Selestat"]["stations"]])

In [5]:
print("Site:", SITE, "/", "Stations:", STATIONS)

Site: A2350200 / Stations: A235020001,A235020002,A235020003

# 1. Reload the data

In [49]:
min_date, max_date = "20070101", "20260601"
basename = f"hubeau_{HUBEAU_DATA_ENDPOINT}_{SITE}_{min_date}_{max_date}"

In [ ]:
filepath_1 = os.path.join(LOCAL_DATA_DIRECTORY, f"{basename}_1.csv")
df = pandas.read_csv(filepath_1)

In [42]:
df["date_obs_elab"] = pandas.to_datetime(df["date_obs_elab"])
df.sort_values(by="date_obs_elab", ascending=True, inplace=True)
display(df.head(20))

,code_site,code_station,date_obs_elab,resultat_obs_elab,longitude,latitude,grandeur_hydro_elab
0,A2350200,A235020001,2007-01-01,958.0,7.459819,48.271833,HIXM
228,A2350200,A235020001,2007-01-01,700.0,7.459819,48.271833,HIXnJ
7240,A2350200,A235020001,2007-01-01,828.0,7.459819,48.271833,QINM
7431,A2350200,A235020001,2007-01-01,828.0,7.459819,48.271833,QINnJ
13957,A2350200,A235020001,2007-01-01,12320.0,7.459819,48.271833,QIXM
14151,A2350200,A235020001,2007-01-01,4500.0,7.459819,48.271833,QIXnJ
20857,A2350200,A235020001,2007-01-01,6198.0,7.459819,48.271833,QmM
21043,A2350200,A235020001,2007-01-01,2501.0,7.459819,48.271833,QmnJ
229,A2350200,A235020001,2007-01-02,821.0,7.459819,48.271833,HIXnJ
7432,A2350200,A235020001,2007-01-02,2557.0,7.459819,48.271833,QINnJ
14152,A2350200,A235020001,2007-01-02,7930.0,7.459819,48.271833,QIXnJ
21044,A2350200,A235020001,2007-01-02,5360.0,7.459819,48.271833,QmnJ
21045,A2350200,A235020001,2007-01-03,6811.0,7.459819,48.271833,QmnJ
14153,A2350200,A235020001,2007-01-03,7600.0,7.459819,48.271833,QIXnJ
230,A2350200,A235020001,2007-01-03,810.0,7.459819,48.271833,HIXnJ
7433,A2350200,A235020001,2007-01-03,6363.0,7.459819,48.271833,QINnJ
231,A2350200,A235020001,2007-01-04,797.0,7.459819,48.271833,HIXnJ
7434,A2350200,A235020001,2007-01-04,6101.0,7.459819,48.271833,QINnJ
14154,A2350200,A235020001,2007-01-04,7210.0,7.459819,48.271833,QIXnJ
21046,A2350200,A235020001,2007-01-04,6600.0,7.459819,48.271833,QmnJ

# 2. Explore

In [65]:
display(df["grandeur_hydro_elab"].value_counts())

grandeur_hydro_elab
HIXnJ    7012
QIXnJ    6706
QINnJ    6526
QmnJ     6521
HIXM      228
QIXM      194
QINM      191
QmM       186
Name: count, dtype: int64

In [38]:
display(df[df["grandeur_hydro_elab"] == "HIXnJ"])

,code_site,code_station,date_obs_elab,resultat_obs_elab,longitude,latitude,grandeur_hydro_elab
228,A2350200,A235020001,2007-01-01,700.0,7.459819,48.271833,HIXnJ
229,A2350200,A235020001,2007-01-02,821.0,7.459819,48.271833,HIXnJ
230,A2350200,A235020001,2007-01-03,810.0,7.459819,48.271833,HIXnJ
231,A2350200,A235020001,2007-01-04,797.0,7.459819,48.271833,HIXnJ
232,A2350200,A235020001,2007-01-05,795.0,7.459819,48.271833,HIXnJ
...,...,...,...,...,...,...,...
7235,A2350200,A235020001,2026-05-28,503.0,7.459819,48.271833,HIXnJ
7236,A2350200,A235020001,2026-05-29,499.0,7.459819,48.271833,HIXnJ
7237,A2350200,A235020001,2026-05-30,493.0,7.459819,48.271833,HIXnJ
7238,A2350200,A235020001,2026-05-31,528.0,7.459819,48.271833,HIXnJ
7239,A2350200,A235020001,2026-06-01,542.0,7.459819,48.271833,HIXnJ

In [78]:
display(df[["code_site", "code_station", "date_obs_elab"]].value_counts())

code_site  code_station  date_obs_elab
A2350200   A235020001    2007-01-01       8
                         2007-02-01       8
                         2007-03-01       8
                         2007-04-01       8
                         2007-05-01       8
                                         ..
                         2018-10-23       1
                         2018-10-24       1
                         2018-10-25       1
                         2018-10-26       1
                         2018-10-27       1
Name: count, Length: 7013, dtype: int64

In [79]:
display(df[df["date_obs_elab"] == "2007-01-01"])

,code_site,code_station,date_obs_elab,resultat_obs_elab,longitude,latitude,grandeur_hydro_elab
0,A2350200,A235020001,2007-01-01,958.0,7.459819,48.271833,HIXM
934,A2350200,A235020001,2007-01-01,700.0,7.459819,48.271833,HIXnJ
29452,A2350200,A235020001,2007-01-01,828.0,7.459819,48.271833,QINM
30362,A2350200,A235020001,2007-01-01,828.0,7.459819,48.271833,QINnJ
58516,A2350200,A235020001,2007-01-01,12320.0,7.459819,48.271833,QIXM
59443,A2350200,A235020001,2007-01-01,4500.0,7.459819,48.271833,QIXnJ
87609,A2350200,A235020001,2007-01-01,6198.0,7.459819,48.271833,QmM
88538,A2350200,A235020001,2007-01-01,2501.0,7.459819,48.271833,QmnJ

In [80]:
display(df[df["date_obs_elab"] == "2018-10-27"])

,code_site,code_station,date_obs_elab,resultat_obs_elab,longitude,latitude,grandeur_hydro_elab
5251,A2350200,A235020001,2018-10-27,71.0,7.459819,48.271833,HIXnJ

In [81]:
display(df[df["date_obs_elab"] == "2018-10-26"])

,code_site,code_station,date_obs_elab,resultat_obs_elab,longitude,latitude,grandeur_hydro_elab
5250,A2350200,A235020001,2018-10-26,3.0,7.459819,48.271833,HIXnJ

# 3. Pivot quantities

In [ ]:
df_2 = df.pivot_table(
    index=["code_site", "code_station", "date_obs_elab", "longitude", "latitude"],
    columns="grandeur_hydro_elab",
    values="resultat_obs_elab",
    aggfunc="first")
df_2 = df_2.reset_index()
df_2.columns.name = None

In [ ]:
display(df_2.head(20))

,code_site,code_station,date_obs_elab,longitude,latitude,HIXM,HIXnJ,QINM,QINnJ,QIXM,QIXnJ,QmM,QmnJ
0,A2350200,A235020001,2007-01-01,7.459819,48.271833,958.0,700.0,828.0,828.0,12320.0,4500.0,6198.0,2501.0
1,A2350200,A235020001,2007-01-02,7.459819,48.271833,NaN,821.0,NaN,2557.0,NaN,7930.0,NaN,5360.0
2,A2350200,A235020001,2007-01-03,7.459819,48.271833,NaN,810.0,NaN,6363.0,NaN,7600.0,NaN,6811.0
3,A2350200,A235020001,2007-01-04,7.459819,48.271833,NaN,797.0,NaN,6101.0,NaN,7210.0,NaN,6600.0
4,A2350200,A235020001,2007-01-05,7.459819,48.271833,NaN,795.0,NaN,6279.0,NaN,7152.0,NaN,6657.0
5,A2350200,A235020001,2007-01-06,7.459819,48.271833,NaN,777.0,NaN,6101.0,NaN,6610.0,NaN,6329.0
6,A2350200,A235020001,2007-01-07,7.459819,48.271833,NaN,822.0,NaN,6392.0,NaN,7960.0,NaN,7087.0
7,A2350200,A235020001,2007-01-08,7.459819,48.271833,NaN,811.0,NaN,6580.0,NaN,7630.0,NaN,6989.0
8,A2350200,A235020001,2007-01-09,7.459819,48.271833,NaN,791.0,NaN,6134.0,NaN,7030.0,NaN,6731.0
9,A2350200,A235020001,2007-01-10,7.459819,48.271833,NaN,765.0,NaN,5667.0,NaN,6266.0,NaN,5899.0
10,A2350200,A235020001,2007-01-11,7.459819,48.271833,NaN,863.0,NaN,6266.0,NaN,9200.0,NaN,7020.0
11,A2350200,A235020001,2007-01-12,7.459819,48.271833,NaN,958.0,NaN,6623.0,NaN,12320.0,NaN,8762.0
12,A2350200,A235020001,2007-01-13,7.459819,48.271833,NaN,777.0,NaN,5880.0,NaN,6623.0,NaN,6318.0
13,A2350200,A235020001,2007-01-14,7.459819,48.271833,NaN,751.0,NaN,5227.0,NaN,5880.0,NaN,5638.0
14,A2350200,A235020001,2007-01-15,7.459819,48.271833,NaN,727.0,NaN,4503.0,NaN,5227.0,NaN,4808.0
15,A2350200,A235020001,2007-01-16,7.459819,48.271833,NaN,700.0,NaN,4157.0,NaN,4503.0,NaN,4330.0
16,A2350200,A235020001,2007-01-17,7.459819,48.271833,NaN,683.0,NaN,3628.0,NaN,4157.0,NaN,3819.0
17,A2350200,A235020001,2007-01-18,7.459819,48.271833,NaN,715.0,NaN,3651.0,NaN,4920.0,NaN,3942.0
18,A2350200,A235020001,2007-01-19,7.459819,48.271833,NaN,886.0,NaN,4920.0,NaN,9952.0,NaN,8643.0
19,A2350200,A235020001,2007-01-20,7.459819,48.271833,NaN,861.0,NaN,8896.0,NaN,9152.0,NaN,9038.0

In [ ]:
df_2.info()

<class 'pandas.DataFrame'>
RangeIndex: 7013 entries, 0 to 7012
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   code_site      7013 non-null   str
 1   code_station   7013 non-null   str
 2   date_obs_elab  7013 non-null   datetime64[us]
 3   longitude      7013 non-null   float64
 4   latitude       7013 non-null   float64
 5   HIXM           228 non-null    float64
 6   HIXnJ          7012 non-null   float64
 7   QINM           191 non-null    float64
 8   QINnJ          6526 non-null   float64
 9   QIXM           194 non-null    float64
 10  QIXnJ          6706 non-null   float64
 11  QmM            186 non-null    float64
 12  QmnJ           6521 non-null   float64
dtypes: datetime64[us](1), float64(10), str(2)
memory usage: 837.4 KB

# 10. Save the dataframe

In [ ]:
filepath_2 = os.path.join(LOCAL_DATA_DIRECTORY, f"{basename}_2.csv")
df_2.to_csv(filepath_2, index=False, encoding="utf-8")

In [ ]:

filesize_in_kb = os.path.getsize(filepath_2) / 1024
print(f">>> saved : \"{filepath_2}\" ({len(df_2)} records, {filesize_in_kb:.0f} Kb)")

>>> saved : "c:\Users\nicolas\Repositories\Jedha\Shares\M11\nowcast-flood-risk\data\hubeau\hubeau_obs_elab_A2350200_20070101_20260601_2.csv" (7013 records, 584 Kb)